default_stages: [commit]

repos:
-   repo: local
    hooks:
  -   id: commitizen
        name: Running commitizen
        entry: cz check --commit-msg-file
        language: system
        stages: [commit-msg]

