default_stages: [commit]

repos:
- repo: local
  hooks:
  - id: isort
    name: Running isort
    entry: isort
    language: python
    types: [python]
  - id: black
    name: Running black
    entry: black
    language: python
    types: [python]
  - id: flake8
    name: Running flake8
    entry: flake8 --count
    language: python
    types: [python]
  - id: mypy
    name: Running mypy
    entry: mypy
    language: python
    types: [python]
  - id: commitizen
    name: Running commitizen
    entry: cz check --commit-msg-file
    language: system
    stages: [commit-msg]
